sudo: false
language: node_js
node_js:
- '16'
notifications:
    email: false
branches:
  only:
  - master
  - packages/functional
  - packages/EventMap
  - packages/Middleware
cache:
  directories:
  - node_modules
before_install:
- npm update
install:
- npm install

matrix:
  include:
  - name: harbor/utils
    env: PACKAGE_LOCATION=.
    if: branc = master
  - name: functional
    env: PACKAGE_LOCATION=packages/functional
    if: branch = packages/functional
  - name: EventMap
    env: PACKAGE_LOCATION=packages/EventMap
    if: branch = packages/EventMap
  - name: Logger
    env: PACKAGE_LOCATION=packages/Middleware
    if: branch = packages/Middleware

script:
  - cd $PACKAGE_LOCATION
  - npm run test
