sudo: false
language: node_js
node_js:
- '16'
notifications:
    email: false
branches:
  only:
  - master
  - packages/functional
  - packages/EventMap
  - packages/Middleware
  - packages/linkProp
  - packages/StateChange
  - packages/testUtils
  - packages/DataElement
cache:
  directories:
  - node_modules
before_install:
- npm update
install:
- npm install

matrix:
  include:
  - name: domx
    env: PACKAGE_LOCATION=.
    if: branch = master
  - name: functional
    env: PACKAGE_LOCATION=packages/functional
    if: branch = packages/functional
  - name: EventMap
    env: PACKAGE_LOCATION=packages/EventMap
    if: branch = packages/EventMap
  - name: Logger
    env: PACKAGE_LOCATION=packages/Middleware
    if: branch = packages/Middleware
  - name: linkProp
    env: PACKAGE_LOCATION=packages/linkProp
    if: branch = packages/linkProp
  - name: StateChange
    env: PACKAGE_LOCATION=packages/StateChange
    if: branch = packages/StateChange
  - name: testUtils
    env: PACKAGE_LOCATION=packages/testUtils
    if: branch = packages/testUtils
  - name: DataElement
    env: PACKAGE_LOCATION=packages/DataElement
    if: branch = packages/DataElement

script:
  - npm run clean
  - npm run build
  - npm run test $PACKAGE_LOCATION
