sudo: false
language: node_js
node_js:
- '16'
notifications:
    email: false
branches:
  only:
  - master
cache:
  directories:
  - node_modules
before_install:
- npm update
install:
- npm install

matrix:
    include:
        - env: TARGET=packages/functional
        - env: TARGET=packages/EventMap
        - env: TARGET=packages/Logger

script:
- npm run test
- if .travis/build-condition.sh $TRAVIS_COMMIT_RANGE $TARGET; then echo "$TARGET is being built" && cd $TARGET && npm install && npm run test; else echo "$TARGET is NOT being built"; fi
