sudo: false
language: node_js
node_js:
- '16'
notifications:
    email: false
branches:
  only:
  - master
cache:
  directories:
  - node_modules
before_install:
- npm update
install:
- npm install

matrix:
  include:
  - name: harbor/utils
    env: PACKAGE_LOCATION=.
  - name: functional
    env: PACKAGE_LOCATION=packages/functional
    if: branch = functional
  - name: EventMap
    env: PACKAGE_LOCATION=packages/EventMap
    if: branch = EventMap
  - name: Logger
    env: PACKAGE_LOCATION=packages/Logger
    if: branch = Logger

script:
  - cd $PACKAGE_LOCATION
  - npm run test
